Mod08/Labfiles/Solution/Client/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Website.Models;

namespace Client.Controllers
{
    public class DepartmentController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public DepartmentController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/Department");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Department> departments = await response.Content.ReadAsAsync<IEnumerable<Department>>();
                return View(departments);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Mod08/Labfiles/Solution/Client/Controllers/JobApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Website.Models;

namespace Client.Controllers
{
    public class JobApplicationController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public JobApplicationController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateEmployeeRequirementsDropDownListAsync();
            return View();
        }

        private async Task PopulateEmployeeRequirementsDropDownListAsync()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/Vacancy");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<EmployeeRequirements> employeeRequirements = await response.Content.ReadAsAsync<IEnumerable<EmployeeRequirements>>();
                ViewBag.EmployeeRequirements = new SelectList(employeeRequirements, "Id", "JobTitle");
            }
        }

        public IActionResult ThankYou()
        {
            return View();
        }
    }
}

Mod08/Labfiles/Solution/Client/Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Website.Models;

namespace Client.Controllers
{
    public class MeetingController : Controller
    {
        private IHttpClientFactory _httpClientFactory;

        public MeetingController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateDepartmentsDropDownListAsync();
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePostAsync(Meeting meeting)
        {
            HttpClient httpclient = _httpClientFactory.CreateClient();
            HttpResponseMessage response = await httpclient.PostAsJsonAsync("http://localhost:54517/api/Meeting", meeting);
            if (response.IsSuccessStatusCode)
            {
                Meeting resMeeting = await response.Content.ReadAsAsync<Meeting>();
                return RedirectToAction("ThankYou", new { id = resMeeting.Id });
            }
            else
            {
                return View("Error");
            }
        }

        private async Task PopulateDepartmentsDropDownListAsync()
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/Department");
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Department> departments = await response.Content.ReadAsAsync<IEnumerable<Department>>();
                ViewBag.Departments = new SelectList(departments, "Id", "Name");
            }
        }

        public async Task<IActionResult> ThankYou(int id)
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://localhost:54517");
            HttpResponseMessage response = await httpClient.GetAsync("api/Meeting/" + id);
            if (response.IsSuccessStatusCode)
            {
                Meeting meeting = await response.Content.ReadAsAsync<Meeting>();
                return View(meeting);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Mod08/Labfiles/Solution/Client/Controllers/VacancyController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class VacancyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Mod08/Labfiles/Solution/Client/Views/Department/Index.cshtml
@model IEnumerable<Website.Models.Department>

@{
    ViewData["Title"] = "Index";
}

<h2 class="title">
    <span class="span-col-s">Departments</span>
</h2>

<div class="container">
    @foreach (var item in Model)
    {
        <div class="photo-index-card">
            <div class="image-wrapper">
                <img class="photo-display-img" src="~/images/desk.jpg" />
            </div>
            <div class="display-picture-title">
                <h6>@Html.DisplayFor(modelItem => item.Name)</h6>
                <h6>@Html.DisplayFor(modelItem => item.Street)</h6>
                <h6>@Html.DisplayFor(modelItem => item.PhoneNumber)</h6>
            </div>
        </div>
    }
</div>

Mod08/Labfiles/Solution/Client/Views/JobApplication/Create.cshtml
@using Website.Models
@model Website.Models.JobApplication

@{
    ViewData["Title"] = "Create";
}

<div class="row justify-content-center">
    <div class="col-5">
        <form method="post" enctype="multipart/form-data" asp-action="Create" id="submit-form">
            <div class="form-group row">
                <label asp-for="EmployeeRequirements" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <select asp-for="EmployeeRequirementsId" asp-items="ViewBag.EmployeeRequirements" class="form-control" placeholder="Job title" required>
                    </select>
                    <span asp-validation-for="EmployeeRequirementsId"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="FirstName" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="FirstName" type="text" class="form-control" placeholder="First Name" required>
                    <span asp-validation-for="FirstName"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="LastName" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="LastName" type="text" class="form-control" placeholder="Last Name" required>
                    <span asp-validation-for="LastName"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PhoneNumber" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="Number" required>
                    <span asp-validation-for="PhoneNumber"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Email" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="Email" type="email" class="form-control" placeholder="Email" required>
                    <span asp-validation-for="Email"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Address" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="Address" type="text" class="form-control" placeholder="Address" required>
                    <span asp-validation-for="Address"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button id="btn-post" type="submit" class="btn btn-outline-success">
                        Apply For a Job
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/post-vacancy.js"></script>
    }

Mod08/Labfiles/Solution/Client/Views/JobApplication/ThankYou.cshtml
@{
    ViewData["Title"] = "ThankYou";
}

<h2 class="title">
    <span class="span-col-f">Thank you for applying.</span>
    <span class="span-col-s">We will get back to you soon.</span>
</h2>

Mod08/Labfiles/Solution/Client/Views/Meeting/Create.cshtml
@model Website.Models.Meeting

@{
    ViewData["Title"] = "Create";
}


<div class="row justify-content-center">
    <div class="col-5">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div class="form-group row">
                <label asp-for="Department" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <select asp-for="DepartmentId" asp-items="ViewBag.Departments" type="text" class="form-control" placeholder="Department" required>
                    </select>
                    <span asp-validation-for="DepartmentId"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="FirstName" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="FirstName" type="text" class="form-control" placeholder="First Name" required>
                    <span asp-validation-for="FirstName"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="LastName" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="LastName" type="text" class="form-control" placeholder="Last Name" required>
                    <span asp-validation-for="LastName"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PhoneNumber" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="Number" required>
                    <span asp-validation-for="PhoneNumber"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="ReservationTime" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="ReservationTime" type="datetime-local" class="form-control" placeholder="Reservation Time">
                    <span asp-validation-for="ReservationTime"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Participants" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="Participants" type="number" class="form-control" placeholder="Number Participants">
                    <span asp-validation-for="Participants"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button id="formButton" type="submit" class="btn btn-outline-success">
                        Book Meeting
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts{
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Mod08/Labfiles/Solution/Client/Views/Meeting/ThankYou.cshtml
@model Website.Models.Meeting

@{
    ViewData["Title"] = "ThankYou";
}

<h2 class="title">
    <span class="span-col-f">Thank you for booking your meeting.</span>
</h2>

<h2 class="title second-title">Meeting Information:</h2>
<div class="container-info">
    <div>
        <span class="display-label">
            Name:
        </span>
        <br />
        <span class="display-field">
            @Html.DisplayFor(model => model.FirstName)  @Html.DisplayFor(model => model.LastName)
        </span>
    </div>

    <div>
        <span class="display-label">
            Phone number to contact:
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.PhoneNumber)
        </span>
    </div>

    <div>
        <span class="display-label">
            @Html.DisplayNameFor(model => model.ReservationTime):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.ReservationTime)
        </span>
    </div>
</div>

Mod08/Labfiles/Solution/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/umd/popper-lite.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/menu-active.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom p-1">
        <div class="collapse navbar-collapse" id="nav-content">
            <ul class="navbar-nav" id="nav-content">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Department")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "Meeting")">Book Meeting</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Vacancy")">We Are Hiring</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "JobApplication")">Submit Job Application</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="main-title">
        <h1>Welcome to Our School</h1>
    </div>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

Mod08/Labfiles/Solution/Client/Views/Vacancy/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2 class="title">
    <span class="span-col-f">Join our team!</span>
    <button class="btn btn-outline-success" type="button" onclick="location.href='@Url.Action("Create", "JobApplication")'">Submit Job Application</button>
</h2>
<div class="container">
</div>
@section Scripts {
    <script src="~/js/get-vacancy.js"></script>
    }